// src/svelteapp/src/routes/menu/+page.svelte
﻿<script>
  import AppHeading from "$lib/common/components/AppHeading.svelte";
  import AppVariant from "$lib/common/components/AppVariant.svelte";
</script>

<AppHeading>Menu</AppHeading>
<div class="w-1/2 mx-auto flex flex-col gap-6">
  <a href="translations">
    <AppVariant>Translations</AppVariant>
  </a>
  <a href="quiz">
    <AppVariant>Quiz</AppVariant>
  </a>
</div>

// src/clientapp/src/Menu/Menu.tsx
import React from "react";
import {Link} from "react-router-dom";
import AppButton from "common/components/AppButton/AppButton";
import Display from "common/components/Display/Display";

const Menu = () => {
  return (
    <>
      <AppButton className="mb-4">
        <Link to="/translations">
          <Display size={4} text="Translations"/>
        </Link>
      </AppButton>
      <AppButton>
        <Link to="/quiz">
          <Display size={4} text="Quiz"/>
        </Link>
      </AppButton>
    </>
  );
};

export default Menu;
