// src/svelteapp/src/routes/translations/TranslationRow.svelte
﻿<script lang="ts">
  import type { TranslationResponse } from "$lib/services/translation-service";

  export let translation: TranslationResponse;
  export let rowIndex: number;

  function rowValues(translation: TranslationResponse, rowIndex: number) {
    return [
      rowIndex + 1,
      translation.first.language,
      translation.second.language,
      translation.first.string,
      translation.second.string,
    ];
  }

</script>

<tr>
  {#each rowValues(translation, rowIndex) as value}
    <td class="text-center">{value}</td>
  {/each}
  <td class="text-center">
    <i class="fa fa-trash"></i>
  </td>
</tr>

// src/clientapp/src/Translations/Table/Row/TranslationRow.tsx
import { TranslationResponse } from "common/services/translation-service";
import "./TranslationRow.scss";

interface TranslationRowProps {
  translation: TranslationResponse;
  index: number;
}

export default function TranslationRow({ translation, index }: TranslationRowProps) {
  return (
    <tr className="translation-row text-center">
      <th scope="row">{index}</th>
      <td className="w-20">{translation.first.language}</td>
      <td className="w-20">{translation.second.language}</td>
      <td className="w-30">{translation.first.string}</td>
      <td className="w-30">{translation.second.string}</td>
    </tr>
  );
};
